version: '3'

services:

  mariadb:
    image: 'mariadb:10.7'
    restart: on-failure
    environment:
      MARIADB_DATABASE: db
      MARIADB_USER: user
      MARIADB_PASSWORD: pass
      MARIADB_ROOT_PASSWORD: pass
    volumes:
      - 'mariadb:/var/lib/mysql:rw'
    expose:
      - '3306'

  ms-backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    expose:
      - '8080'

volumes:
  mariadb:
